name: GitHub Actions Demo
on: [push]
jobs:
  First Jobber:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1"
      - run: echo "Step 2"
  Second Jobber:
    runs-on: ubuntu-latest
    steps:
      - name: "Hotstepper"
        run: |
          echo "lit"
