name: GitHub Actions Demo
on: [push]
jobs:
  First_Jobber:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1"
      - run: echo "Step 2"
  Second_Jobber:
    runs-on: ubuntu-latest
    steps:
      - name: Here comes the Hot Stepper
        run: |
          echo "lit"
