name: GitHub Actions Demo
on: [push]
jobs:
  first_jobber:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1"
      - run: echo "Step 2"
  second_jobber:
    needs: first_jobber
    runs-on: ubuntu-latest
    steps:
      - name: Here comes the Hot Stepper
        run: |
          echo "lit"
  turd_jobber:
    needs: first_jobber
    runs-on: ubuntu-latest
    steps:
      - name: Gimme the loot
        run: |-
          echo "I'm a bastard!!!"
